apiVersion: v1
kind: Service
metadata:
  name: atlas-migrations-service
  namespace: atlas-operator-ns
spec:
  selector:
    app: atlas-migrations
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
  type: LoadBalancer
