#apiVersion: v1
#kind: Secret
#metadata:
#  name: postgres-credentials
#  namespace: atlas-operator-ns
#type: Opaque
#stringData:
#  url: "postgresql://myuser:mypassword@my-postgresql-rw:5432/mydatabase"
#  username: "myuser"
#  password: "mypassword"
#  database: "mydatabase"
#  host: "my-postgresql-rw"
#  port: "5432"
#  # Postgres superuser credentials
#  postgres-password: "adminpassword"

